on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - run: echo 'Hello, world!'
  # boo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo 'Boo! 👻'
  boo:
    uses: vvv/toybox/.github/workflows/reusable.boo.yml@main
