name: w.ci

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello:
    name: w.ci.j.hello
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v2
      - run: echo 'Hello, world!'
  boo:
    name: w.ci.j.boo
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Boo! 👻'
  boo-caller:
    name: w.ci.j.boo-caller
    uses: vvv/toybox/.github/workflows/reusable.named-boo.yml@main
